@baseUrl = http://onboarding.local


###
GET {{baseUrl}}/user
Authorization: Bearer 5fc5582f25c031.17535080

###
POST {{baseUrl}}/user

{
    "firstname": "Annika",
    "lastname": "Vennemann",
    "email": "annivenne@ohhh.org",
    "password": "hello",
    "startdate": "01-01-2021"
}

###
Post {{baseUrl}}/login

{
    "email": "annivenne@ohhh.org",
    "password": "hello"
}


###
