@baseUrl = http://onboarding.local

###
POST {{baseUrl}}/user

{
    "firstname": "Annika",
    "lastname": "Vennemann",
    "email": "annika@ohhh.org",
    "password": "helloohhh",
    "startdate": "01-01-2021"
}

###
Post {{baseUrl}}/login

{
    "email": "annika@ohhh.org",
    "password": "helloohhh"
}

###
GET {{baseUrl}}/user
Authorization: Bearer 5fd87b8d664567.74956045


###
GET {{baseUrl}}/checklist
Authorization: Bearer 5fd87b8d664567.74956045

