@baseUrl = http://onboarding.local


###
GET {{baseUrl}}/user
Authorization: Bearer 5fc64246f0f203.03500178

###
POST {{baseUrl}}/user

{
    "firstname": "Annika",
    "lastname": "Vennemann",
    "email": "annivenne@ohhh.org",
    "password": "helloohhh",
    "startdate": "01-01-2021"
}

###
Post {{baseUrl}}/login

{
    "email": "annivenne@ohhh.org",
    "password": "helloohhh"
}


###
